# -*- mode: ruby -*-
# vi: set ft=ruby :

SERVER_HOSTNAME = "aadnaneS"
SERVER_IP = "192.168.56.110"
SERVER_RAM = 1024
OS = "bento/debian-11"
CPU = 1

Vagrant.configure("2") do |config|

  # Server Machine
  config.vm.define "aadnaneS" do |server|
  config.vm.box = OS
  server.vm.hostname = SERVER_HOSTNAME
  server.vm.network "private_network", ip: SERVER_IP
  server.vm.provider "virtualbox" do |vb|
    vb.memory = SERVER_RAM
    vb.cpus = CPU
    vb.name = "aadnaneS"
  end
  server.vm.provision "shell", path: "scripts/server_conf.sh" , args: [SERVER_IP]
end
end
