# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # The definition of the first VM
  config.vm.define 'aadnaneS' do |vagrant1|

    # The Operating system
    vagrant1.vm.box = "ubuntu/trusty64"

    # The system spec
    vagrant1.vm.provider "virtualBox" do |box1|
      box1.memory = 512
      box1.cpu = 1
      box1.name = "aadnaneS"
    end

    # The netwrok setting
    vagrant1.vm.network "public_network", ip: "192.168.56.110", bridge: "ens33"

    # The startup script
    # config.vm.provision "shell", path: "./tools/installServer.sh"
  end

  # The definition of the first VM
  config.vm.define 'yait-iazSW' do |vagrant2|

    # The Operating system
    vagrant2.vm.box = "ubuntu/trusty64"

    # The system spec
    vagrant2.vm.provider "virtualBox" do |box2|
      box2.memory = 512
      box2.cpu = 1
      box2.name = "yait-iazSW"
    end

    # The netwrok setting
    vagrant2.vm.network "public_network", ip: "192.168.56.111", bridge: "ens33"

    # The startup script
    # config.vm.provision "shell", path: "./tools/installServerWorker.sh"
  end

end
